### ISSUE TITLE
Booking View Add a Resource

### ISSUE THREAD

**Issue by barnwellrd** [barnwellrd/Phoenix-Resource-Management-System#49]
What view will Add a Resource direct to? Is someone already creating it?

**Comment by litelime** [comment]
The nav buttons I had since the very beginning didnt really put thought into them. Although the intention was that this link would be for an admin to add a resource. I think a team is working on that functionality. Not sure how it is intended to be accessed though.

**Comment by barnwellrd** [comment]
Okay, we will leave this open for now for reference and I'll open up
additional issues for the add resource view. Once we are sure you don't
need a button or whatever, you can just delete them from the view and close
this issue
